version: '3.8'

services:
  mcp-mulesoft-server:
    build: .
    container_name: mcp-mulesoft-server
    environment:
      - ANYPOINT_URL=https://anypoint.mulesoft.com
      - CLIENT_ID=
      - CLIENT_SECRET=
      - ORG_ID=
    stdin_open: true
    tty: true
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    
  # Opcionalmente, você pode adicionar um service para debug HTTP
  mcp-mulesoft-debug:
    build: .
    container_name: mcp-mulesoft-debug
    environment:
      - ANYPOINT_URL=https://anypoint.mulesoft.com
      - CLIENT_ID=
      - CLIENT_SECRET=
      - ORG_ID=
      - MCP_DEBUG=true
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    profiles:
      - debug
